layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

  social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: ben-morris-ldn
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: borrislearns
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Go
    web_url: https://github.com/golang
    image_url: https://raw.githubusercontent.com/ashleymcnamara/gophers/master/BLUE_GOPHER.png

  - name: Flutter
    web_url: https://github.com/flutter/flutter#
    image_url: https://raw.githubusercontent.com/dart-lang/site-shared/master/src/_assets/image/flutter/icon/64.png

  - name: Dart Lang
    web_url: https://github.com/dart-lang
    image_url: https://raw.githubusercontent.com/dart-lang/site-shared/master/src/_assets/image/dart/logo/1080.png